name: build-and-publish

concurrency:
    cancel-in-progress: true
    group: build-and-publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init zarf cache
        uses: actions/cache@v3
        with:
          path: "~/.zarf-cache"
          key: zarf-cache

      - name: Install zarf
        uses: supplypike/setup-bin@v3
        with:
          # renovate: zarf-uri datasource=github-tags depName=defenseunicorns/zarf
          uri: 'https://github.com/defenseunicorns/zarf/releases/download/v0.29.2/zarf_v0.29.2_Linux_amd64'
          name: 'zarf'
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: 'v0.29.2'

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}

      ####
      # Build and publish dependency packages to use in a dev UDS Bundle
      ####
      - name: Build and publish dev-dependency mattermost-postgres package
        run: cd utils/pkg-deps/mattermost/postgres && zarf package create --confirm --no-progress --output oci://ghcr.io/defenseunicorns/uds-capability/mattermost/dev-dependency

      - name: Build and publish dev-dependency mattermost-minio package
        run: cd utils/pkg-deps/mattermost/minio && zarf package create --confirm --no-progress --output oci://ghcr.io/defenseunicorns/uds-capability/mattermost/dev-dependency

      ####
      # Build and publish capability package and skeleton
      ####
      - name: Build mattermost-operator package
        run: zarf package create --confirm --no-progress

      - name: Publish mattermost-operator package
        run: zarf package publish zarf-package-mattermost-operator-amd64-*.tar.zst oci://ghcr.io/defenseunicorns/uds-capability --no-progress

      - name: Publish mattermost-operator skeleton
        run: zarf package publish . oci://ghcr.io/defenseunicorns/uds-capability --no-progress
